```{r 加载及各包作用}
# Vector：矢量数据，人文社科领域，sf包
# Raster：栅格数据，环境科学领域，Raster包
library(sf)          # classes and functions for vector data
library(raster)      # classes and functions for raster data
library(spData)        # load geographic data
library(spDataLarge)   # load larger geographic data
names(world)
plot(world)
world_mini = world[1:2, 1:3]
world_mini
```

```{R 简单功能}
# MULTILINESTRING 多线条
# MULTIPOINT      多点
# MULTIPOLYGON    多重多边形
# POLYGON         多边形
# POINT           点
# LINESTRING      线
```

```{R}
library(sf)
world_asia = world[world$continent == "Asia", ]
asia = st_union(world_asia)
plot(world["pop"], reset = FALSE)   # DONT RESET
plot(asia, add = TRUE, col = "yellow") # ADD
```

```{R 基本Plot参数}
plot(world["continent"], reset = FALSE)
cex = sqrt(world$pop) / 10000
world_cents = st_centroid(world, of_largest = TRUE) # 多边形转化为点
plot(st_geometry(world_cents), add = TRUE, cex = cex)
# 具体区域
india = world[world$name_long == "India", ]
plot(st_geometry(india), expandBB = c(0, 0.2, 0.1, 1), col = "gray", lwd = 3)
plot(world_asia[0], add = TRUE) 
```

```{R smg: Simple feature geometries}
library(sf)
#创建单点
plot(st_point(c(5, 2)))                 # XY point
plot(st_point(c(5, 2, 3)))              # XYZ point
plot(st_point(c(5, 2, 1), dim = "XYM")) # XYM point
plot(st_point(c(5, 2, 3, 1)))           # XYZM point

# the rbind function simplifies the creation of matrices
#多点和线需要矩阵matrix
## MULTIPOINT
multipoint_matrix = rbind(c(5, 2), c(1, 3), c(3, 4), c(3, 2))
plot(st_multipoint(multipoint_matrix))
## LINESTRING
linestring_matrix = rbind(c(1, 5), c(4, 4), c(4, 1), c(2, 2), c(3, 2))
plot(st_linestring(linestring_matrix))

#几何图形需要列表list
## POLYGON
polygon_list = list(rbind(c(1, 5), c(2, 2), c(4, 1), c(4, 4), c(1, 5)))
plot(st_polygon(polygon_list))

## POLYGON with a hole
polygon_border = rbind(c(1, 5), c(2, 2), c(4, 1), c(4, 4), c(1, 5))
polygon_hole = rbind(c(2, 4), c(3, 4), c(3, 3), c(2, 3), c(2, 4))
polygon_with_hole_list = list(polygon_border, polygon_hole)
plot(st_polygon(polygon_with_hole_list))

## MULTILINESTRING
multilinestring_list = list(rbind(c(1, 5), c(4, 4), c(4, 1), c(2, 2), c(3, 2)), 
                            rbind(c(1, 2), c(2, 4)))
plot(st_multilinestring((multilinestring_list)))

## MULTIPOLYGON
multipolygon_list = list(list(rbind(c(1, 5), c(2, 2), c(4, 1), c(4, 4), c(1, 5))),
                         list(rbind(c(0, 2), c(1, 2), c(1, 3), c(0, 3), c(0, 2))))
plot(st_multipolygon(multipolygon_list))

## GEOMETRYCOLLECTION
gemetrycollection_list = list(st_multipoint(multipoint_matrix),
                              st_linestring(linestring_matrix))
plot(st_geometrycollection(gemetrycollection_list))
```

```{R smc: Sinple feature columns 简单特征列}
point1 = st_point(c(5, 2))
point2 = st_point(c(1, 3))
points_sfc = st_sfc(point1, point2)
points_sfc
#sfc中有多组sfg
# sfc POLYGON
polygon_list1 = list(rbind(c(1, 5), c(2, 2), c(4, 1), c(4, 4), c(1, 5)))
polygon1 = st_polygon(polygon_list1)
polygon_list2 = list(rbind(c(0, 2), c(1, 2), c(1, 3), c(0, 3), c(0, 2)))
polygon2 = st_polygon(polygon_list2)
polygon_sfc = st_sfc(polygon1, polygon2)
plot(polygon_sfc)
st_geometry_type(polygon_sfc)

# sfc MULTILINESTRING
multilinestring_list1 = list(rbind(c(1, 5), c(4, 4), c(4, 1), c(2, 2), c(3, 2)), 
                            rbind(c(1, 2), c(2, 4)))
multilinestring1 = st_multilinestring((multilinestring_list1))
multilinestring_list2 = list(rbind(c(2, 9), c(7, 9), c(5, 6), c(4, 7), c(2, 7)), 
                            rbind(c(1, 7), c(3, 8)))
multilinestring2 = st_multilinestring((multilinestring_list2))
multilinestring_sfc = st_sfc(multilinestring1, multilinestring2)
plot(multilinestring_sfc)
st_geometry_type(multilinestring_sfc)

# sfc GEOMETRY
point_multilinestring_sfc = st_sfc(point1, multilinestring1)
plot(point_multilinestring_sfc )
st_geometry_type(point_multilinestring_sfc)
st_crs(points_sfc)
#sfc的坐标参考系统赋值crs
points_sfc_wgs = st_sfc(point1, point2, crs = 4326)
st_crs(points_sfc_wgs)
```

```{R sf Class 类}
lnd_point = st_point(c(0.1, 51.5))        # sfg object 创建sfg
lnd_geom = st_sfc(lnd_point, crs = 4326)  # sfc object sfg转化为sfc带有CRS
lnd_attrib = data.frame(                  # data.frame object
  name = "London",                        # 地点属性存储在dataframe里
  temperature = 25,
  date = as.Date("2017-06-21")
  )
lnd_sf = st_sf(lnd_attrib, geometry = lnd_geom) 
# sf object = 地点属性dataframe+sfc对象
lnd_sf
class(lnd_sf)
```

```{R Raster Data}
library(spDataLarge)
raster_filepath = system.file("raster/srtm.tif", package = "spDataLarge")
new_raster = raster(raster_filepath) # RasterLayer object
new_raster
dim(new_raster)       # 行 列 层
ncell(new_raster)     # 像素数量
res(new_raster)       # 空间分辨率
extent(new_raster)    # 空间范围
crs(new_raster)       # 坐标参考系
inMemory(new_raster)  # 数据存储在内存中还是硬盘上
# help("raster-package") raster函数完整列表
```

```{R Basic map Raster & raster Classes 基本绘图方法 和 Raster类}
plot(new_raster)
# Class Rasterlayer
# 从包中获取Rasterlayer
raster_filepath = system.file("raster/srtm.tif", package = "spDataLarge")
new_raster = raster(raster_filepath)
# 重新创建Rasterlayer
new_raster2 = raster(nrows = 6, ncols = 6, res = 0.5, 
                     xmn = -1.5, xmx = 1.5, ymn = -1.5, ymx = 1.5,
                     vals = 1:36)
# 其他方法1 RasterBrick 单个多光谱卫星文件 单个多层对象 快
multi_raster_file = system.file("raster/landsat.tif", package = "spDataLarge")
r_brick = brick(multi_raster_file) 
r_brick
plot(r_brick)
nlayers(r_brick) # 检查存储在RasterBrick中对象的层数
# 其他方法2 RasterStack 调用不同文件中的Raster对象 慢
raster_on_disk = raster(r_brick, layer = 1)
raster_in_memory = raster(xmn = 301905, xmx = 335745,
                          ymn = 4111245, ymx = 4154085, 
                          res = 30)
values(raster_in_memory) = sample(seq_len(ncell(raster_in_memory)))
crs(raster_in_memory) = crs(raster_on_disk)
r_stack = stack(raster_in_memory, raster_on_disk)
r_stack
plot(r_stack)
```

```{R Coordinate Reference Systems CRS 坐标参考系统}
# epsg          短         两种定义方式
# proj4string   复杂       设定丰富
crs_data = rgdal::make_EPSG()
#View(crs_data)                   #可用的CRS
# 检查对象使用的CRS
vector_filepath = system.file("vector/zion.gpkg", package = "spDataLarge")
new_vector = st_read(vector_filepath)
st_crs(new_vector) # get CRS
new_vector = st_set_crs(new_vector, 4326) # set CRS
projection(new_raster) # get CRS
new_raster3 = new_raster
projection(new_raster3) = "+proj=utm +zone=12 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 
                            +units=m +no_defs" # set CRS
```

```{r Units 单位}
luxembourg = world[world$name_long == "Luxembourg", ] # 卢森堡面积
st_area(luxembourg) # requires the s2 package in recent versions of sf
units::set_units(st_area(luxembourg), km^2) # set 单位 km^2
# 十进制度为单元的 WGS84 投影
res(new_raster)
#使用 UTM 投影，单位会改变
repr = projectRaster(new_raster, crs = 26912)
res(repr)
```

```{r Exercise}
# 用于数据对象summary()的几何列world。输出告诉我们什么：
# 它的几何类型？
# 国家数量？
# 它的坐标参考系统（CRS）？
# 运行在第2.2.4节末尾“生成”图2.5中的世界地图的代码。找出您计算机上的图像与书中的图像之间的两个相似之处和两个不同之处。
# 什么是cex参数做（见?plot）？
# 为什么被cex设置为sqrt(world$pop) / 10000？
# 奖励：尝试不同的方式来可视化全球人口。
# 用于plot()在上下文中创建尼日利亚地图（参见第2.2.4 节）。
# 调整 的lwd、col和expandBB参数plot()。
# 挑战：阅读text()地图的文档并对其进行注释。
# 创建一个RasterLayer名为my_raster10 列和 10 行的空对象。将 0 到 10 之间的随机值分配给新栅格并绘制它。
# raster/nlcd2011.tif从spDataLarge包中读入文件。您可以获得有关此文件属性的哪些信息？
# 提醒：解决方案可以在https://geocompr.github.io在线找到
```

