library(data.table)
library(dplyr)
#==========================
file1=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults1.csv",sep = ',')
file2=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults2.csv",sep = ',')
file3=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults3.csv",sep = ',')
file4=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults4.csv",sep = ',')
file5=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults5.csv",sep = ',')
file6=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults6.csv",sep = ',')
file7=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults7.csv",sep = ',')
file8=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults8.csv",sep = ',')
file9=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults9.csv",sep = ',')
file10=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults10.csv",sep = ',')
file11=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults11.csv",sep = ',')
file12=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults12.csv",sep = ',')
file13=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults13.csv",sep = ',')
file14=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults14.csv",sep = ',')
file15=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults15.csv",sep = ',')
file16=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults16.csv",sep = ',')
file17=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults17.csv",sep = ',')
file18=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults18.csv",sep = ',')
file19=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults19.csv",sep = ',')
file20=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults20.csv",sep = ',')
file21=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults21.csv",sep = ',')
file22=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults22.csv",sep = ',')
file23=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults23.csv",sep = ',')
file24=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults24.csv",sep = ',')
file25=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults25.csv",sep = ',')
file26=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults26.csv",sep = ',')
file27=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults27.csv",sep = ',')
file28=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults28.csv",sep = ',')
file29=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults29.csv",sep = ',')

file30=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults30.csv",sep = ',')
file31=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults31.csv",sep = ',')
file32=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults32.csv",sep = ',')
file33=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults33.csv",sep = ',')
file34=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults34.csv",sep = ',')
file35=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults35.csv",sep = ',')
file36=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults36.csv",sep = ',')
file37=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults37.csv",sep = ',')
file38=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults38.csv",sep = ',')
file39=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults39.csv",sep = ',')

file40=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults40.csv",sep = ',')
file41=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults41.csv",sep = ',')
file42=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults42.csv",sep = ',')
file43=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults43.csv",sep = ',')
file44=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults44.csv",sep = ',')
file45=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults45.csv",sep = ',')
file46=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults46.csv",sep = ',')
file47=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults47.csv",sep = ',')
file48=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults48.csv",sep = ',')
file49=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults49.csv",sep = ',')

file50=fread("/Users/mizexin/Desktop/要查的船/第二次结果/ShipResults50.csv",sep = ',')

data1 = cbind(file1,file2)
data2 = cbind(file3,file4)
data3 = cbind(file5,file6)
data4 = cbind(file7,file8)
data5 = cbind(file9,file10)
data6 = cbind(file11,file12)
data7 = cbind(file13,file14)
data8 = cbind(file15,file16)
data9 = cbind(file17,file18)
data10 = cbind(file19,file20)
data11 = cbind(file21,file22)
data12 = cbind(file23,file24)
data13 = cbind(file25,file26)
data14 = cbind(file27,file28)
data15 = cbind(file29,file30)
data16 = cbind(file31,file32)
data17 = cbind(file33,file34)
data18 = cbind(file35,file36)
data19 = cbind(file37,file38)
data20 = cbind(file39,file40)
data21 = cbind(file41,file42)
data22 = cbind(file43,file44)
data23 = cbind(file45,file46)
data24 = cbind(file47,file48)
data25 = cbind(file49,file50)

rm(file1,file2,file3,file4,file5,file6,file7,file8,file9,file10,file11,file12,file13,file14,file15,file16,file17,file18,file19,file20,file21,file22)
data = rbind(data1,data2,data3,data4,data5,data6,data7,data8,data9,data10,
             data11,data12,data13,data14,data15,data16,data17,data18,data19,data20,
             data21,data22,data23,data24,data25)
data = data[,-(13:14)]
fwrite(data,'/Users/mizexin/Desktop/要查的船/IHS二次查询结果.csv',sep = ',')   

#==========================
data=fread("/Users/mizexin/Desktop/要查的船/IHS初次查询结果.csv",sep = ',')
a = data.table(data$MMSI%>%na.omit(.))
selectmmsi=fread("/Users/mizexin/Desktop/要查的船/selectmmsi.csv",sep = ',')
b = data.table(selectmmsi$mmsi%>%na.omit(.))

s = b[!b$V1 %in% a$V1]

df1<-data.table(s)
fwrite(df1,'/Users/mizexin/Desktop/要查的船/IHS第二次查询列表.csv',sep = ',')

#===========导出未查询到的表===============
file1 = fread("/Users/mizexin/Desktop/要查的船/selectimo.csv",sep = ',')
file2 = fread("/Users/mizexin/Desktop/要查的船/selectmmsi.csv",sep = ',')
file = rbind(file1,file2)

res1 = fread("/Users/mizexin/Desktop/要查的船/imo_result.csv",sep = ',')
res2 = fread("/Users/mizexin/Desktop/要查的船/mmsi_result.csv",sep = ',')
res = rbind(res1,res2)
s = file[!file$mmsi %in% res$MMSI]
ss = s[!s$imoNum %in% res$`IMO/LR/IHS No.`]
fwrite(ss,'/Users/mizexin/Desktop/要查的船/unFound.csv',sep = ',')
